version: '3'

services:

  rest:
    build:
      context: ./rest
    ports:
      - 5001:5000
    env_file:
      ./credentials.env
    volumes:
      - ./rest/src:/app
    container_name: official_rest_server

  ui:
    build:
      context: ./ui
    environment:
      - REST_SERVER=http://rest:5000
    ports:
      - 5000:5000
    env_file:
      ./credentials.env
    volumes:
      - ./ui/src:/app
    container_name: webui

  mysql-db:
    image: mysql:latest
    restart: always
    env_file:
      ./credentials.env
    ports:
      - 3306:3306                     # external port : internal mysql port
    volumes:
      - ./persist_db:/var/lib/mysql   # persist when container is stopped!
    container_name: rest_database

volumes:
  persist_db: